const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let DATA=null,GEO=null,storyMode='aro',exploreMode='resumen',aroFilter='',selected='';
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim().replace(/^SANTIAGO DE CALI$/,'CALI').replace(/^CALIMA$/,'CALIMA EL DARIEN').replace(/^EL DARIEN$/,'CALIMA EL DARIEN').replace(/^BUGA$/,'GUADALAJARA DE BUGA').replace(/^RIO FRIO$/,'RIOFRIO');
const fmt=(n,d=0)=>n==null||n===''?'—':Number(n).toLocaleString('es-CO',{maximumFractionDigits:d,minimumFractionDigits:d});
const byName=()=>Object.fromEntries(DATA.municipios.map(m=>[normalize(m.municipio),m]));
function metric(m,mode){if(!m)return 0;if(mode==='agua')return (m.agua.sistemas_documentados||0)+(m.agua.sistemas_afectacion_documentada||0)*2;if(mode==='eis')return (m.eis.ues_registros_operativos||0)+(m.eis.ues_cementerios||0)+(m.eis.ues_ie_sedes||0)*.25;if(mode==='alimentos')return m.alimentos.despachos||0;return m.score_resumen||0}
const palettes={resumen:['#e7f0f4','#bad9e4','#7ebfd1','#3799b6','#0e6686'],agua:['#e6f3f7','#b4dce6','#6bc1d2','#2395b0','#075c79'],eis:['#e7f4ef','#b9dfd4','#7bc6b3','#369b85','#13685a'],alimentos:['#fff4dc','#f8dd98','#edbf61','#db8d2f','#9a5718']};
const aroColors={'Norte Cartago':'#64a9c3','Centro Tuluá':'#7dac69','Sur Cali':'#e4a248'};
function colorFor(v,max,mode,outside=false,aro=''){if(outside)return '#e5e8eb';if(mode==='aro')return aroColors[aro]||'#e7ecef';if(!v)return '#edf2f5';let q=Math.sqrt(v/Math.max(max,1));let i=Math.min(4,Math.max(0,Math.ceil(q*5)-1));return palettes[mode][i]}
function svgPath(geom,bbox,w=760,h=900,pad=35){const[minx,miny,maxx,maxy]=bbox;let sx=(w-2*pad)/(maxx-minx),sy=(h-2*pad)/(maxy-miny),s=Math.min(sx,sy);let ox=(w-(maxx-minx)*s)/2,oy=(h-(maxy-miny)*s)/2;const pt=([x,y])=>[ox+(x-minx)*s,h-(oy+(y-miny)*s)];function ring(r){return r.map((p,i)=>{let[x,y]=pt(p);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')+' Z'}if(geom.type==='Polygon')return geom.coordinates.map(ring).join(' ');if(geom.type==='MultiPolygon')return geom.coordinates.map(p=>p.map(ring).join(' ')).join(' ');return ''}
function geoBBox(){let xs=[],ys=[];GEO.features.forEach(f=>{let b=f.geometry.type==='Polygon'?f.geometry.coordinates.flat():f.geometry.coordinates.flat(2);b.forEach(p=>{xs.push(p[0]);ys.push(p[1])})});return [Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]}
function detailText(m,mode){if(!m)return 'Fuera del ámbito de competencia UESVALLE.';if(mode==='aro')return `<b>${m.municipio}</b> · ${m.aro}`;if(mode==='agua')return `<b>${m.municipio}</b> · ${m.aro}<br>Sistemas con estado: <b>${fmt(m.agua.sistemas_documentados)}</b> · con afectación: <b>${fmt(m.agua.sistemas_afectacion_documentada)}</b> · restablecidos: <b>${fmt(m.agua.sistemas_restablecidos)}</b>`;if(mode==='eis')return `<b>${m.municipio}</b> · ${m.aro}<br>Registros operativos: <b>${fmt(m.eis.ues_registros_operativos)}</b> · cementerios: <b>${fmt(m.eis.ues_cementerios)}</b> · sedes educativas: <b>${fmt(m.eis.ues_ie_sedes)}</b>`;if(mode==='alimentos')return `<b>${m.municipio}</b> · ${m.aro}<br>Despachos en capa integrada: <b>${fmt(m.alimentos.despachos)}</b>${m.alimentos.peso_t?` · ${fmt(m.alimentos.peso_t,1)} t`:''}<br><small>Subconjunto analítico; no equivale al consolidado logístico completo.</small>`;return `<b>${m.municipio}</b> · ${m.aro}<br>Agua documentada: <b>${fmt(m.agua.sistemas_documentados)}</b> · EIS directos: <b>${fmt(m.eis.ues_registros_operativos)}</b> · despachos en capa: <b>${fmt(m.alimentos.despachos)}</b>`}
function drawMap(svg,mode,{tooltipId=null,detailId=null,clickable=true}={}){if(!svg)return;const bm=byName(),bbox=geoBBox(),vals=GEO.features.map(f=>metric(bm[f.properties.canonical],mode)),max=Math.max(...vals,1);svg.innerHTML='';GEO.features.forEach(f=>{const m=bm[f.properties.canonical];let p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',svgPath(f.geometry,bbox));p.setAttribute('class','muni-path'+(selected===f.properties.canonical?' selected':''));p.setAttribute('fill',colorFor(metric(m,mode),max,mode,f.properties.outside,m?.aro||''));p.dataset.name=f.properties.canonical;p.setAttribute('aria-label',f.properties.name);if(tooltipId){p.addEventListener('mousemove',e=>showTooltip(e,tooltipId,f,m,mode,svg));p.addEventListener('mouseleave',()=>hideTooltip(tooltipId))}if(clickable)p.addEventListener('click',()=>{selected=f.properties.canonical;if(detailId){let d=document.getElementById(detailId);if(d)d.innerHTML=detailText(m,mode)};refreshMaps()});svg.appendChild(p)})}
function showTooltip(e,id,f,m,mode,svg){let tt=document.getElementById(id);if(!tt)return;tt.innerHTML=detailText(m,mode);tt.style.display='block';let r=svg.parentElement.getBoundingClientRect();tt.style.left=(e.clientX-r.left+12)+'px';tt.style.top=(e.clientY-r.top+12)+'px'}function hideTooltip(id){let tt=document.getElementById(id);if(tt)tt.style.display='none'}
function refreshMaps(){drawMap($('#storyMap'),storyMode,{tooltipId:'storyTooltip',detailId:'storyMapDetail'});drawMap($('#waterMap'),'agua',{tooltipId:'waterTooltip'});drawMap($('#eisMap'),'eis',{tooltipId:'eisTooltip'});drawMap($('#exploreMap'),exploreMode,{tooltipId:'exploreTooltip'});}
function setStoryMode(mode){storyMode=mode;const titles={aro:['ÁREAS REGIONALES OPERATIVAS','Cobertura territorial UESVALLE'],resumen:['RESPUESTA INTEGRADA','Síntesis territorial de las tres líneas'],agua:['AGUA PARA CONSUMO HUMANO','Sistemas documentados y afectaciones'],eis:['ESTABLECIMIENTOS DE INTERÉS SANITARIO','Actuaciones y establecimientos priorizados'],alimentos:['ALIMENTOS Y AYUDA HUMANITARIA','Capa integrada de despachos']};$('#storyMapEyebrow').textContent=titles[mode][0];$('#storyMapTitle').textContent=titles[mode][1];$('#aroLegend').style.display=mode==='aro'?'flex':'none';$('#storyMapDetail').innerHTML=selected?detailText(byName()[selected],mode):'Seleccione una línea o un municipio.';drawMap($('#storyMap'),mode,{tooltipId:'storyTooltip',detailId:'storyMapDetail'});}
function renderKpis(){let a=DATA.dashboard_meta.agua,e=DATA.dashboard_meta.eis.uesvalle;$('#waterKpis').innerHTML=[[a.universo,'Sistemas de referencia'],[a.municipios_verificados,'Municipios verificados'],[a.sistemas_documentados,'Sistemas con estado'],[a.sistemas_afectacion_documentada,'Con afectación'],[a.sistemas_restablecidos,'Restablecimientos explícitos']].map(x=>`<div class="mini-kpi"><b>${fmt(x[0])}</b><span>${x[1]}</span></div>`).join('');const pt=e.por_tipo_registro||{};$('#eisKpis').innerHTML=[[pt.ALBERGUE_TEMPORAL||0,'Albergues temporales'],[e.cementerios_evaluados||0,'Cementerios evaluados'],[pt.INSTITUCION_EDUCATIVA||0,'Instituciones educativas'],[pt.ADULTO_MAYOR_GERIATRICO||0,'Protección al adulto mayor']].map(x=>`<div class="mini-kpi"><b>${fmt(x[0])}</b><span>${x[1]}</span></div>`).join('')}
function renderWater(){let w=DATA.water_form_metrics;$('#waterRecent').innerHTML=[[w.sistemas_unicos_formulario,'Sistemas únicos en formulario'],[w.sistemas_con_antecedente_afectacion,'Con antecedente de afectación'],[w.sistemas_con_evidencia_fotografica,'Con evidencia fotográfica'],[w.sistemas_que_reportan_apoyo_inmediato,'Reportan apoyo inmediato']].map(x=>`<div class="recent-kpi"><b>${fmt(x[0])}</b><span>${x[1]}</span></div>`).join('');$('#waterPhotoCases').innerHTML=(DATA.water_photo_cases||[]).map((c,i)=>`<article class="water-story-card ${i%2?'reverse':''}"><div class="water-story-media">${(c.images||[]).map((u,j)=>`<figure class="water-photo ${j===0?'main':''}"><img class="lightbox-img" src="${u}" alt="${c.municipio} · ${c.sistema}"><figcaption>${c.caption}</figcaption></figure>`).join('')}</div><div class="water-story-copy"><span class="place">${c.municipio.toUpperCase()}</span><h3>${c.sistema}</h3><div class="water-status">${c.estado_actual}</div><p>${c.descripcion}</p><dl><div><dt>Componente</dt><dd>${c.componentes}</dd></div><div><dt>Apoyo requerido</dt><dd>${c.apoyo}</dd></div></dl></div></article>`).join('');$('#waterCases').innerHTML=DATA.water_cases.map(c=>`<article class="case-card"><span class="tag">${c.municipio}</span><h3>${c.sistema}</h3><p>${c.descripcion||'Diagnóstico registrado.'}</p><div class="case-meta"><span>Estado<b>${c.estado_actual||'—'}</b></span><span>Componente<b>${c.componentes||'—'}</b></span><span>Apoyo<b>${c.requiere_apoyo||'—'}</b></span></div></article>`).join('')}
function renderEis(){let t=$('#eisTour');t.innerHTML=DATA.eis_cases.map(c=>`<article class="tour-card"><div class="tour-media ${c.image2?'two':''}"><img class="lightbox-img" src="${c.image}" alt="${c.municipio}">${c.image2?`<img class="lightbox-img" src="${c.image2}" alt="${c.municipio}">`:''}</div><div class="tour-copy"><span class="place">${c.municipio.toUpperCase()}</span><h3>${c.title}</h3><p>${c.text}</p><p class="caption">${c.caption}</p></div></article>`).join('')}
function renderFood(){let f=DATA.food_context;$('#foodProcess').innerHTML=f.process.map((x,i)=>`${i?'<i>→</i>':''}<span>${x}</span>`).join('');$('#foodContext').innerHTML=`<article class="context-card"><span class="small">LICORERA · CORTE ${f.licorera.corte}</span><div><b>${fmt(f.licorera.despachos)}</b> despachos documentados</div><div><b>${f.licorera.toneladas}</b></div><p>${f.licorera.note}</p></article><article class="context-card"><span class="small">CARTAGO · CORTE ${f.cartago.corte}</span><div><b>${fmt(f.cartago.despachos)}</b> formatos consolidados</div><div><b>${fmt(f.cartago.destinos)}</b> destinos · <b>${f.cartago.toneladas}</b></div><p>${f.cartago.note}</p></article>`}
function renderArticulation(){const a=DATA.articulacion||{};$('#articulationIntro').textContent=a.intro||'';$('#articulationEntities').innerHTML=(a.entidades||[]).map(e=>`<article class="entity-card"><span class="entity-date">${e.date||''}</span><h3>${e.name}</h3><b>${e.kind}</b><p>${e.text}</p></article>`).join('');$('#articulationCase').innerHTML=`<span class="chapter">CASO DE ARTICULACIÓN PARA LA RECUPERACIÓN</span><p>${a.case||''}</p>`}
function renderTimeline(){const showDate=s=>{let x=String(s).replaceAll('2026-08-','');x=x.replace('/','–');return x+' AGO 2026'};$('#timeline').innerHTML=DATA.hitos.map(h=>`<article class="time-item"><time>${showDate(h.fecha)}</time><div><h3>${h.fase}</h3><p>${h.hito}</p></div></article>`).join('')}
function modeValueText(m,mode){if(mode==='agua')return `${fmt(m.agua.sistemas_documentados)} sistemas`;if(mode==='eis')return `${fmt(m.eis.ues_registros_operativos)} registros`;if(mode==='alimentos')return `${fmt(m.alimentos.despachos)} despachos`;return `índice ${fmt(m.score_resumen)}`}
function renderRanking(){let q=normalize($('#municipioSearch').value),arr=DATA.municipios.filter(m=>(!aroFilter||m.aro===aroFilter)&&(!q||normalize(m.municipio).includes(q)));arr.sort((a,b)=>metric(b,exploreMode)-metric(a,exploreMode));$('#rankTitle').textContent=`${arr.length} municipios`;$('#rankNote').textContent=exploreMode==='alimentos'?'capa integrada':exploreMode==='eis'?'actuación directa UESVALLE':'corte normalizado';$('#municipioList').innerHTML=arr.map(m=>`<div class="muni-row" data-muni="${normalize(m.municipio)}"><div><b>${m.municipio}</b><small>${m.aro}</small></div><span class="value">${modeValueText(m,exploreMode)}</span></div>`).join('');$$('.muni-row').forEach(r=>r.onclick=()=>{selected=r.dataset.muni;refreshMaps()})}
function setupExplorer(){$$('#modeButtons button').forEach(b=>b.onclick=()=>{$$('#modeButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active');exploreMode=b.dataset.mode;drawMap($('#exploreMap'),exploreMode,{tooltipId:'exploreTooltip'});renderRanking()});$$('#aroButtons button').forEach(b=>b.onclick=()=>{$$('#aroButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active');aroFilter=b.dataset.aro;renderRanking()});$('#municipioSearch').oninput=renderRanking;renderRanking()}
function setupLightbox(){const box=$('#lightbox'),img=$('#lightboxImage'),cap=$('#lightboxCaption');function bind(){$$('.lightbox-img').forEach(el=>{el.onclick=()=>{img.src=el.src;cap.textContent=el.closest('figure')?.querySelector('figcaption')?.innerText||el.alt||'';box.classList.add('open');box.setAttribute('aria-hidden','false')}})}bind();$('#lightboxClose').onclick=()=>{box.classList.remove('open');box.setAttribute('aria-hidden','true')};box.onclick=e=>{if(e.target===box){box.classList.remove('open');box.setAttribute('aria-hidden','true')}};document.addEventListener('keydown',e=>{if(e.key==='Escape')box.classList.remove('open')})}
function setupUI(){$$('#storyMapButtons button').forEach(b=>b.onclick=()=>{$$('#storyMapButtons button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setStoryMode(b.dataset.mode)});$('#presentBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};window.addEventListener('scroll',()=>{let h=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=(h>0?(scrollY/h*100):0)+'%'});}
async function init(){[DATA,GEO]=await Promise.all([fetch('data/story_content.json').then(r=>r.json()),fetch('data/municipios_story.geojson').then(r=>r.json())]);renderKpis();renderWater();renderEis();renderFood();renderArticulation();renderTimeline();setStoryMode('aro');drawMap($('#waterMap'),'agua',{tooltipId:'waterTooltip'});drawMap($('#eisMap'),'eis',{tooltipId:'eisTooltip'});drawMap($('#exploreMap'),'resumen',{tooltipId:'exploreTooltip'});setupExplorer();setupUI();$('#diagLink').href=DATA.links.diagnostico;$('#currentLink').href=DATA.links.respuesta_actual;$('#edanLink').href=DATA.links.edan;setTimeout(setupLightbox,30)}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('afterbegin','<div style="position:fixed;z-index:9999;bottom:10px;left:10px;background:#7c1d1d;color:#fff;padding:10px;border-radius:8px">Error al cargar datos. Abra el Story mediante ABRIR_STORY.bat.</div>')});