(() => {
  'use strict';
  const DATA = window.ACUEDUCTOS_DATA || [];
  const META = window.ACUEDUCTOS_META || {};
  const MUN = window.ACUEDUCTOS_MUNICIPAL || [];
  const INV = window.ACUEDUCTOS_INVERSIONES || [];
  const METHOD = window.ACUEDUCTOS_METODOLOGIA || [];
  const SOURCES = window.ACUEDUCTOS_FUENTES || [];
  const LAYER_URL = 'https://services5.arcgis.com/l23kE3b7uPnZIuaB/arcgis/rest/services/CARTOGRAFIA_BASE/FeatureServer/2';
  const qs=(s,e=document)=>e.querySelector(s), qsa=(s,e=document)=>[...e.querySelectorAll(s)];
  const esc=t=>String(t??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const fmt=n=>Number.isFinite(+n)?new Intl.NumberFormat('es-CO',{maximumFractionDigits:0}).format(+n):'Sin dato';
  const pct=n=>new Intl.NumberFormat('es-CO',{minimumFractionDigits:1,maximumFractionDigits:1}).format(+n||0)+' %';
  const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(+n||0);
  const moneyM=n=>'$'+new Intl.NumberFormat('es-CO',{maximumFractionDigits:1}).format((+n||0)/1e6)+' M';
  const short=(t,n=150)=>!t?'Sin información':(String(t).length>n?String(t).slice(0,n-1)+'…':String(t));
  const norm=v=>String(v??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim();
  const canonical=v=>{const x=norm(v);if(x==='SANTIAGO DE CALI')return'CALI';if(x==='BUGA')return'GUADALAJARA DE BUGA';if(['CALIMA','EL DARIEN','CALIMA EL DARIEN'].includes(x))return'CALIMA EL DARIEN';return x;};
  const priorityClass=p=>({'ALTA':'high','MEDIA':'medium','BAJA':'low','POR VALIDAR':'unknown'})[p]||'unknown';
  const priOrder={'ALTA':0,'MEDIA':1,'BAJA':2,'POR VALIDAR':3};
  let page=1, pageSize=8, GEO=null, SELECTED_MUN='', DETAIL_PHOTO_INDEX=0;
  const CARD_PHOTO_INDEX=new Map();

  function initTheme(){
    const saved=localStorage.getItem('acueductos-theme-v131-presentacion')||'light';
    document.documentElement.dataset.theme=saved;updateThemeLabel(saved);
    qs('#theme-toggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('acueductos-theme-v131-presentacion',next);updateThemeLabel(next);});
  }
  function updateThemeLabel(t){qs('#theme-label').textContent=t==='dark'?'Modo claro':'Modo oscuro';qs('#theme-icon').textContent=t==='dark'?'☀':'☾';}

  function renderKPIs(){
    const items=[
      {key:'universe',v:fmt(META.universo_acueductos),l:'Universo de Acueductos',s:'Sistemas únicos consolidados'},
      {key:'diagnostic',v:pct(META.porcentaje_diagnosticado),l:'% Acueductos Diagnosticados',s:`${fmt(META.diagnosticados)} de ${fmt(META.universo_acueductos)} con estado operativo conocido`,click:'map'},
      {key:'population',v:fmt(META.poblacion_afectada_reportada),l:'Población afectada',s:'Población afectada reportada en los acueductos afectados'},
      {key:'suspended',v:fmt(META.suspendidos_afectados),l:'Acueductos suspendidos',s:'Estado operativo según consolidado V1.2'},
      {key:'affected',v:fmt(META.acueductos_afectados),l:'Acueductos con afectaciones',s:'Afectación asociada al evento',click:'affected'},
      {key:'investment',v:moneyM(META.inversion_aproximada_total_cop),l:'Inversión Aproximada',s:'Acueducto + alcantarillado',click:'investment'}
    ];
    qs('#kpis').innerHTML=items.map(x=>`<article class="kpi ${x.key} ${x.click?'clickable':''}" data-kpi="${x.click||''}" ${x.click?'role="button" tabindex="0"':''}><span class="value">${x.v}</span><span class="label">${x.l}</span><span class="sub">${x.s}</span>${x.click?'<span class="kpi-action">Ver detalle →</span>':''}</article>`).join('');
    qsa('[data-kpi]').forEach(k=>{const run=()=>{if(k.dataset.kpi==='map')openDiagnosticMap();else if(k.dataset.kpi==='affected')openAffectedBreakdown();else if(k.dataset.kpi==='investment')goTab('inv');};k.addEventListener('click',run);k.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}});});
  }

  function initTabs(){qsa('.tab').forEach(b=>b.addEventListener('click',()=>goTab(b.dataset.tab)));qsa('[data-go-tab]').forEach(b=>b.addEventListener('click',()=>goTab(b.dataset.goTab)));}
  function goTab(tab){qsa('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));qsa('.tab-panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+tab));if(tab==='diag')renderCards();if(tab==='pri')renderPriorityTable();if(tab==='inv')renderInvestments();setTimeout(()=>qs('.module-tabs').scrollIntoView({behavior:'smooth',block:'start'}),20);}

  function fillSelect(id,vals){const el=qs(id);vals.filter(Boolean).forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));}
  function initFilters(){
    fillSelect('#filter-mun',[...new Set(DATA.map(d=>d.municipio))].sort((a,b)=>a.localeCompare(b,'es')));
    fillSelect('#filter-pri',['ALTA','MEDIA','BAJA','POR VALIDAR']);
    fillSelect('#filter-op',['NORMAL','PARCIAL','SUSPENDIDO','POR VALIDAR']);
    fillSelect('#filter-comp',[...new Set(DATA.flatMap(d=>d.componentes||[]))].sort((a,b)=>a.localeCompare(b,'es')));
    ['#search','#filter-mun','#filter-pri','#filter-op','#filter-comp','#filter-photo'].forEach(id=>qs(id).addEventListener(id==='#search'?'input':'change',onFilterChange));
    qs('#clear-filters').addEventListener('click',()=>{['#search','#filter-mun','#filter-pri','#filter-op','#filter-comp','#filter-photo'].forEach(id=>qs(id).value='');SELECTED_MUN='';onFilterChange();});
  }
  function filters(){return{q:qs('#search').value.trim().toLowerCase(),mun:qs('#filter-mun').value,pri:qs('#filter-pri').value,op:qs('#filter-op').value,comp:qs('#filter-comp').value,photo:qs('#filter-photo').value};}
  function matchCommon(d,f){return(!f.q||[d.municipio,d.sistema,d.localidad,d.afectacion,d.accion_requerida].join(' ').toLowerCase().includes(f.q))&&(!f.mun||d.municipio===f.mun)&&(!f.pri||d.prioridad===f.pri)&&(!f.op||d.estado_operativo===f.op)&&(!f.comp||(d.componentes||[]).includes(f.comp));}
  function filteredAffected(){const f=filters();return DATA.filter(d=>matchCommon(d,f)&&(!f.photo||(f.photo==='con'?(d.fotos_publicadas||0)>0:(d.fotos_publicadas||0)===0)));}
  function filteredInvestments(){const f=filters();return INV.filter(d=>matchCommon(d,f));}
  function onFilterChange(){page=1;const list=filteredAffected();qs('#active-filter-text').textContent=list.length===DATA.length?`Vista departamental · ${list.length} acueductos afectados.`:`Consulta filtrada · ${list.length} de ${DATA.length} acueductos afectados.`;renderSummary();renderMunicipalRanking();renderAffectedSummary();renderCards();renderPriorityTable();renderInvestments();SELECTED_MUN=filters().mun||'';renderAllMaps();}

  function groupCount(list,key){return list.reduce((o,d)=>{const k=typeof key==='function'?key(d):d[key];o[k]=(o[k]||0)+1;return o;},{});}
  function barRows(entries,max,type='normal',formatter=null,filterType=''){max=max||1;const f=filters();const activeValue=filterType==='op'?f.op:filterType==='pri'?f.pri:filterType==='comp'?f.comp:'';return entries.map(([label,value])=>{let cls='';if(type==='priority')cls=priorityClass(label);else if(label==='NORMAL')cls='normal';else if(label==='PARCIAL')cls='partial';else if(label==='SUSPENDIDO')cls='suspended';else if(label==='POR VALIDAR')cls='unknown';const v=formatter?formatter(value):fmt(value),interactive=!!filterType&&value>0,selected=interactive&&activeValue===label;return `<div class="bar-row ${interactive?'interactive':''} ${selected?'selected':''}" ${interactive?`data-summary-filter="${filterType}" data-summary-value="${esc(label)}" role="button" tabindex="0"`:''}><span class="bar-label" title="${esc(label)}">${esc(label)}</span><div class="bar-track"><div class="bar-fill ${cls}" style="width:${value>0?Math.max(2,value/max*100):0}%"></div></div><span class="bar-count">${v}</span></div>`;}).join('');}

  function bindSummaryBars(){qsa('[data-summary-filter]').forEach(row=>{const run=()=>{const map={op:'#filter-op',pri:'#filter-pri',comp:'#filter-comp'},sel=qs(map[row.dataset.summaryFilter]);if(!sel)return;sel.value=sel.value===row.dataset.summaryValue?'':row.dataset.summaryValue;onFilterChange();};row.addEventListener('click',run);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}});});}

  function renderSummary(){
    const list=filteredAffected();
    const op=[['NORMAL',0],['PARCIAL',0],['SUSPENDIDO',0],['POR VALIDAR',0]];list.forEach(d=>{const i=op.findIndex(x=>x[0]===d.estado_operativo);if(i>=0)op[i][1]++;});
    const pr=[['ALTA',0],['MEDIA',0],['BAJA',0],['POR VALIDAR',0]];list.forEach(d=>{const i=pr.findIndex(x=>x[0]===d.prioridad);if(i>=0)pr[i][1]++;});
    const comps={};list.forEach(d=>(d.componentes||[]).forEach(c=>comps[c]=(comps[c]||0)+1));const top=Object.entries(comps).sort((a,b)=>b[1]-a[1]).slice(0,10);
    qs('#operation-bars').innerHTML=barRows(op,Math.max(...op.map(x=>x[1]),1),'normal',null,'op');qs('#priority-bars').innerHTML=barRows(pr,Math.max(...pr.map(x=>x[1]),1),'priority',null,'pri');qs('#component-bars').innerHTML=barRows(top,Math.max(...top.map(x=>x[1]),1),'normal',null,'comp');bindSummaryBars();
    qs('#operation-note').textContent=`${list.length} acueductos · clic para filtrar`;qs('#priority-note').textContent=`${list.length} acueductos · clic para filtrar`;
    qs('#money-total').textContent=money(META.inversion_aproximada_total_cop);qs('#money-acueducto').textContent=money(META.inversion_acueducto_cop);qs('#money-alcantarillado').textContent=money(META.inversion_alcantarillado_cop);
  }

  function municipalForCurrentFilters(){
    const f=filters(), aff=filteredAffected(), affBy=groupCount(aff,'municipio');
    return MUN.filter(m=>!f.mun||m.municipio===f.mun).map(m=>({...m,afectados_filtrados:affBy[m.municipio]||0}));
  }
  function renderMunicipalRanking(){const arr=municipalForCurrentFilters().filter(m=>m.afectados_filtrados>0||(!filters().mun&&m.afectados>0)).sort((a,b)=>(b.afectados_filtrados||b.afectados)-(a.afectados_filtrados||a.afectados)||b.inversion_total-a.inversion_total).slice(0,12);qs('#municipal-ranking').innerHTML=arr.map(m=>`<div class="mun-rank"><div class="mun-rank-head"><span>${esc(m.municipio)}</span><strong>${fmt(m.afectados_filtrados||m.afectados)} afectados</strong></div><div class="mun-rank-meta"><span>${pct(m.porcentaje_diagnosticado)} diagnosticado</span><span>${moneyM(m.inversion_total)}</span></div></div>`).join('')||'<div class="panel-card">Sin resultados para los filtros seleccionados.</div>';}

  function renderAffectedSummary(){const list=filteredAffected(),op=groupCount(list,'estado_operativo');qs('#affected-summary').innerHTML=[['NORMAL',op.NORMAL||0],['PARCIAL',op.PARCIAL||0],['SUSPENDIDO',op.SUSPENDIDO||0],['POR VALIDAR',op['POR VALIDAR']||0]].map(x=>`<span class="summary-chip">${esc(x[0])}: <strong>${fmt(x[1])}</strong></span>`).join('');const published=list.reduce((a,d)=>a+(d.fotos_publicadas||0),0),systems=list.filter(d=>(d.fotos_publicadas||0)>0).length;qs('#photo-publication-summary').innerHTML=`<span><strong>${fmt(published)}</strong> fotografías publicadas · <strong>${fmt(systems)}</strong> acueductos con galería</span><small>Registro web sin metadatos EXIF. La evidencia institucional adicional permanece fuera del repositorio público.</small>`;}
  function cardPhotoHTML(d){
    const imgs=d.imagenes||[];
    if(!imgs.length)return `<div class="record-photo empty"><div class="photo-placeholder"><span>Sin fotografía publicada</span><small>${fmt(d.fotos||0)} evidencia(s) referenciada(s) en fuente</small></div></div>`;
    const idx=Math.min(CARD_PHOTO_INDEX.get(d.id)||0,imgs.length-1),src=imgs[idx];
    return `<div class="record-photo" data-photo-card="${esc(d.id)}"><img src="${esc(src)}" alt="Evidencia de ${esc(d.sistema)}" loading="lazy"><div class="photo-gradient"></div><button class="photo-nav prev" data-photo-prev="${esc(d.id)}" aria-label="Foto anterior">‹</button><button class="photo-nav next" data-photo-next="${esc(d.id)}" aria-label="Foto siguiente">›</button><span class="photo-count">${idx+1} / ${imgs.length}</span><span class="photo-source">Registro fotográfico</span></div>`;
  }

  function card(d){return `<article class="record-card">${cardPhotoHTML(d)}<div class="record-visual"><div class="municipality-head"><span class="municipality-label">MUNICIPIO</span><span class="place">${esc(d.municipio)}</span></div><span class="priority-chip p-${priorityClass(d.prioridad)}">${esc(d.prioridad)}</span></div><div class="card-body"><h3>${esc(d.sistema)}</h3><div class="card-metrics"><div class="metric-cell"><span>Operación</span><b>${esc(d.estado_operativo)}</b></div><div class="metric-cell"><span>Población afectada</span><b>${fmt(d.poblacion_afectada)}</b></div><div class="metric-cell"><span>Inversión</span><b>${moneyM(d.inversion_cop)}</b></div></div><div class="finding"><strong>¿Qué se afectó?</strong>${esc(short(d.afectacion,185))}</div><div class="finding"><strong>¿Qué se debe hacer?</strong>${esc(short(d.accion_requerida,180))}</div><div class="flags">${(d.componentes||[]).map(x=>`<span class="flag">${esc(x)}</span>`).join('')}</div><div class="card-actions"><button class="detail-btn" data-id="${esc(d.id)}">Ver ficha completa →</button></div></div></article>`;}

  function cycleCardPhoto(id,dir){const d=DATA.find(x=>x.id===id),imgs=d?.imagenes||[];if(imgs.length<2)return;let i=CARD_PHOTO_INDEX.get(id)||0;i=(i+dir+imgs.length)%imgs.length;CARD_PHOTO_INDEX.set(id,i);renderCards();}

  function renderCards(){const list=filteredAffected(),maxPage=Math.max(1,Math.ceil(list.length/pageSize));if(page>maxPage)page=maxPage;const slice=list.slice((page-1)*pageSize,page*pageSize);qs('#affected-count').textContent=`Mostrando ${slice.length?((page-1)*pageSize+1):0}–${Math.min(page*pageSize,list.length)} de ${list.length} acueductos`;qs('#affected-cards').innerHTML=slice.map(card).join('')||'<div class="panel-card">No hay acueductos que coincidan con los filtros.</div>';qs('#pagination').innerHTML=Array.from({length:maxPage},(_,i)=>i+1).slice(Math.max(0,page-4),Math.min(maxPage,page+3)).map(p=>`<button class="page-btn ${p===page?'active':''}" data-page="${p}">${p}</button>`).join('');qsa('.page-btn').forEach(b=>b.addEventListener('click',()=>{page=+b.dataset.page;renderCards();}));qsa('.detail-btn').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.id)));qsa('[data-photo-prev]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();cycleCardPhoto(b.dataset.photoPrev,-1);}));qsa('[data-photo-next]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();cycleCardPhoto(b.dataset.photoNext,1);}));qsa('.record-photo img').forEach(img=>img.addEventListener('click',()=>{const id=img.closest('[data-photo-card]')?.dataset.photoCard;if(id)openDetail(id);}));}

  function detailGalleryHTML(d){const imgs=d.imagenes||[];if(!imgs.length)return `<div class="evidence-box"><strong>Sin fotografías publicadas en esta versión</strong><div class="small-note">La fuente consolidada referencia ${fmt(d.fotos||0)} evidencia(s). La evidencia adicional permanece en el repositorio institucional privado.</div></div>`;DETAIL_PHOTO_INDEX=Math.min(DETAIL_PHOTO_INDEX,imgs.length-1);return `<div class="detail-gallery" data-gallery-id="${esc(d.id)}"><div class="detail-photo-stage"><img id="detail-photo-main" src="${esc(imgs[DETAIL_PHOTO_INDEX])}" alt="Registro fotográfico de ${esc(d.sistema)}"><button class="photo-nav prev detail-prev" aria-label="Foto anterior">‹</button><button class="photo-nav next detail-next" aria-label="Foto siguiente">›</button><span class="photo-count" id="detail-photo-count">${DETAIL_PHOTO_INDEX+1} / ${imgs.length}</span></div><div class="detail-thumbs">${imgs.map((src,i)=>`<button class="detail-thumb ${i===DETAIL_PHOTO_INDEX?'active':''}" data-detail-photo="${i}"><img src="${esc(src)}" alt="Miniatura ${i+1}" loading="lazy"></button>`).join('')}</div><div class="small-note">${fmt(imgs.length)} fotografía${imgs.length===1?'':'s'} publicada${imgs.length===1?'':'s'} · archivos optimizados para web y sin metadatos EXIF.</div></div>`;}

  function refreshDetailGallery(d){const imgs=d.imagenes||[];if(!imgs.length)return;const img=qs('#detail-photo-main'),count=qs('#detail-photo-count');if(img)img.src=imgs[DETAIL_PHOTO_INDEX];if(count)count.textContent=`${DETAIL_PHOTO_INDEX+1} / ${imgs.length}`;qsa('.detail-thumb').forEach((b,i)=>b.classList.toggle('active',i===DETAIL_PHOTO_INDEX));}

  function bindDetailGallery(d){const imgs=d.imagenes||[];if(!imgs.length)return;qs('.detail-prev')?.addEventListener('click',()=>{DETAIL_PHOTO_INDEX=(DETAIL_PHOTO_INDEX-1+imgs.length)%imgs.length;refreshDetailGallery(d);});qs('.detail-next')?.addEventListener('click',()=>{DETAIL_PHOTO_INDEX=(DETAIL_PHOTO_INDEX+1)%imgs.length;refreshDetailGallery(d);});qsa('[data-detail-photo]').forEach(b=>b.addEventListener('click',()=>{DETAIL_PHOTO_INDEX=+b.dataset.detailPhoto;refreshDetailGallery(d);}));}

  function openDetail(id){const d=DATA.find(x=>x.id===id);if(!d)return;DETAIL_PHOTO_INDEX=0;qs('#modal-content').innerHTML=`<div class="modal-hero"><span class="eyebrow light">MUNICIPIO · ${esc(d.municipio)}</span><h2>${esc(d.sistema)}</h2><p>${esc(d.localidad||'Localidad no especificada')}</p></div><div class="modal-body"><div class="detail-grid"><div class="detail-item"><span>Prioridad</span><strong>${esc(d.prioridad)}</strong></div><div class="detail-item"><span>Operación</span><strong>${esc(d.estado_operativo)}</strong></div><div class="detail-item"><span>Población afectada</span><strong>${fmt(d.poblacion_afectada)}</strong></div><div class="detail-item"><span>Inversión aproximada</span><strong>${money(d.inversion_cop)}</strong></div></div><div class="detail-section"><h3>Registro fotográfico</h3>${detailGalleryHTML(d)}</div><div class="detail-section"><h3>¿Qué se afectó?</h3><div class="detail-text">${esc(d.afectacion||'Sin detalle adicional')}</div></div><div class="detail-section"><h3>¿Qué se debe hacer?</h3><div class="detail-text">${esc(d.accion_requerida||'Sin acción específica reportada')}</div></div><div class="detail-section"><h3>Componentes relacionados</h3><div class="flags">${(d.componentes||[]).map(x=>`<span class="flag">${esc(x)}</span>`).join('')}</div></div><div class="detail-section"><h3>Fuentes</h3><div class="detail-text">${esc(d.fuentes)}</div></div></div>`;openModal('detail-modal');bindDetailGallery(d);}

  function renderPriorityTable(){const list=filteredAffected().slice().sort((a,b)=>(priOrder[a.prioridad]??9)-(priOrder[b.prioridad]??9)||(b.poblacion_afectada||0)-(a.poblacion_afectada||0)||(b.inversion_cop||0)-(a.inversion_cop||0));const c=groupCount(list,'prioridad');qs('#high-count').textContent=c.ALTA||0;qs('#med-count').textContent=c.MEDIA||0;qs('#low-count').textContent=c.BAJA||0;qs('#unk-count').textContent=c['POR VALIDAR']||0;qs('#priority-table tbody').innerHTML=list.map(d=>`<tr><td><span class="priority-chip p-${priorityClass(d.prioridad)}">${esc(d.prioridad)}</span></td><td>${esc(d.municipio)}</td><td><strong>${esc(d.sistema)}</strong></td><td>${esc(d.estado_operativo)}</td><td>${fmt(d.poblacion_afectada)}</td><td>${esc(short(d.afectacion,145))}</td><td>${esc(short(d.accion_requerida,145))}</td><td class="money">${moneyM(d.inversion_cop)}</td></tr>`).join('')||'<tr><td colspan="8">Sin resultados para los filtros seleccionados.</td></tr>';}

  function renderInvestments(){const list=filteredInvestments();const total=list.reduce((a,d)=>a+(+d.inversion_total||0),0),acu=list.reduce((a,d)=>a+(+d.inversion_acueducto||0),0),alc=list.reduce((a,d)=>a+(+d.inversion_alcantarillado||0),0);const noFilters=Object.values(filters()).every(v=>!v);qs('#inv-total').textContent=money(noFilters?META.inversion_aproximada_total_cop:total);qs('#inv-acu').textContent=money(noFilters?META.inversion_acueducto_cop:acu);qs('#inv-alc').textContent=money(noFilters?META.inversion_alcantarillado_cop:alc);const baseTotal=noFilters?META.inversion_aproximada_total_cop:total,baseAcu=noFilters?META.inversion_acueducto_cop:acu;qs('#inv-acu-pct').textContent=pct(baseTotal?baseAcu/baseTotal*100:0);
    const byMun={};list.forEach(d=>byMun[d.municipio]=(byMun[d.municipio]||0)+d.inversion_total);const topM=Object.entries(byMun).sort((a,b)=>b[1]-a[1]).slice(0,12);qs('#investment-municipality-bars').innerHTML=barRows(topM,Math.max(...topM.map(x=>x[1]),1),'normal',moneyM);
    const service=[['ACUEDUCTO',acu],['ALCANTARILLADO',alc]];qs('#investment-service-bars').innerHTML=barRows(service,Math.max(...service.map(x=>x[1]),1),'normal',moneyM);
    const top=list.slice().sort((a,b)=>b.inversion_total-a.inversion_total).slice(0,18);qs('#investment-table tbody').innerHTML=top.map((d,i)=>`<tr><td>${i+1}</td><td>${esc(d.municipio)}</td><td><strong>${esc(d.sistema)}</strong></td><td><span class="priority-chip p-${priorityClass(d.prioridad)}">${esc(d.prioridad)}</span></td><td>${esc(d.estado_operativo)}</td><td class="money">${moneyM(d.inversion_total)}</td><td>${esc(short(d.accion_requerida,170))}</td></tr>`).join('')||'<tr><td colspan="7">Sin inversiones para la consulta.</td></tr>';}

  function renderMethodology(){qs('#method-grid').innerHTML=METHOD.map(x=>`<article class="method-card"><h3>${esc(x.item)}</h3><p>${esc(x.descripcion)}</p></article>`).join('');qs('#sources-grid').innerHTML=SOURCES.map(x=>`<article class="source-card"><h3>${esc(x.FUENTE||'Fuente')}</h3><p>${esc(x.USO||'')}</p><span class="source-tag">${esc(x.INCORPORACION||'')}</span></article>`).join('');}

  function openModal(id){const m=qs('#'+id);m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
  function closeModal(id){const m=qs('#'+id);m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';}
  qsa('[data-close]').forEach(el=>el.addEventListener('click',()=>{const map={detail:'detail-modal',map:'diagnostic-map-modal',affected:'affected-modal'};closeModal(map[el.dataset.close]);}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape')qsa('.modal.open').forEach(m=>closeModal(m.id));});

  function openAffectedBreakdown(){const items=[['NORMAL',META.operacion_normal_afectados,'#5caf7e'],['PARCIAL',META.operacion_parcial_afectados,'#eaa050'],['SUSPENDIDO',META.suspendidos_afectados,'#df6868'],['POR VALIDAR',META.operacion_por_validar_afectados,'#8399a3']];const max=Math.max(...items.map(x=>x[1]),1);qs('#affected-breakdown').innerHTML=items.map(x=>`<div class="affected-op-row"><span>${x[0]}</span><div class="track"><div class="fill" style="width:${x[1]?Math.max(2,x[1]/max*100):0}%;background:${x[2]}"></div></div><strong>${fmt(x[1])}</strong></div>`).join('');openModal('affected-modal');}
  qs('#go-diagnosis').addEventListener('click',()=>{closeModal('affected-modal');goTab('diag');});

  function diagnosticColor(v){if(v>=100)return'#2c7e58';if(v>=75)return'#75ad78';if(v>=50)return'#d9bd4f';if(v>=25)return'#e99a52';return'#d96b6b';}
  function getFeatureMunicipality(p={}){return p.MPIO_CNMBRE||p.MPIO_CNMBR||p.MUNICIPIO||p.NOM_MUN||p.NOMBRE||p.MPIO||p.NAME||'';}
  function queryURL(){const q=new URLSearchParams({where:'1=1',outFields:'*',returnGeometry:'true',outSR:'4326',f:'geojson'});return`${LAYER_URL}/query?${q}`;}
  async function loadGeo(){if(GEO)return GEO;const r=await fetch(queryURL(),{cache:'force-cache'});if(!r.ok)throw new Error(`Cartografía HTTP ${r.status}`);GEO=await r.json();if(GEO.type!=='FeatureCollection')throw new Error('GeoJSON municipal inválido');return GEO;}
  function geometryBounds(geo){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const walk=c=>{if(typeof c[0]==='number'){minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1]);}else c.forEach(walk);};geo.features.forEach(f=>walk(f.geometry.coordinates));return{minX,minY,maxX,maxY};}
  function ringsFromGeometry(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates;if(g.type==='MultiPolygon')return g.coordinates.flat();return[];}
  function mapData(name){return MUN.find(m=>canonical(m.municipio)===canonical(name));}
  function pathForFeature(f,b,W=760,H=760,pad=22){const sx=(W-2*pad)/(b.maxX-b.minX),sy=(H-2*pad)/(b.maxY-b.minY),scale=Math.min(sx,sy),dx=(W-(b.maxX-b.minX)*scale)/2,dy=(H-(b.maxY-b.minY)*scale)/2;const pt=([x,y])=>[dx+(x-b.minX)*scale,H-(dy+(y-b.minY)*scale)];return ringsFromGeometry(f.geometry).map(r=>r.map((p,i)=>{const [x,y]=pt(p);return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;}).join(' ')+' Z').join(' ');}
  async function renderGeoMap(svgId,selectedId,tooltipId){const svg=qs('#'+svgId),selected=qs('#'+selectedId),tip=qs('#'+tooltipId);try{const geo=await loadGeo(),b=geometryBounds(geo);svg.innerHTML=geo.features.map((f,i)=>{const name=getFeatureMunicipality(f.properties),d=mapData(name),v=d?d.porcentaje_diagnosticado:0,sel=SELECTED_MUN&&canonical(SELECTED_MUN)===canonical(name);return`<path class="municipality-path ${sel?'selected':''}" data-index="${i}" d="${pathForFeature(f,b)}" fill="${d?diagnosticColor(v):'#7b8c94'}" fill-rule="evenodd"></path>`;}).join('');qsa('.municipality-path',svg).forEach(p=>{const f=geo.features[+p.dataset.index],name=getFeatureMunicipality(f.properties),d=mapData(name);p.addEventListener('mousemove',e=>{const rect=svg.parentElement.getBoundingClientRect();tip.innerHTML=`<strong>${esc(name)}</strong><br>${d?pct(d.porcentaje_diagnosticado)+' diagnosticado':'Sin coincidencia en consolidado'}`;tip.style.left=(e.clientX-rect.left+12)+'px';tip.style.top=(e.clientY-rect.top+12)+'px';tip.hidden=false;});p.addEventListener('mouseleave',()=>tip.hidden=true);p.addEventListener('click',()=>{SELECTED_MUN=d?d.municipio:name;showMunicipalDiagnostic(d,selected);renderAllMaps();});});}catch(err){console.error(err);svg.innerHTML='<text x="380" y="370" text-anchor="middle" fill="currentColor" font-size="18">No fue posible cargar la cartografía municipal.</text><text x="380" y="400" text-anchor="middle" fill="currentColor" font-size="12">Verifique la conexión a internet.</text>';}}
  function showMunicipalDiagnostic(d,target){if(!d){target.innerHTML='<p>Sin coincidencia municipal.</p>';return;}target.innerHTML=`<h4>${esc(d.municipio)}</h4><div class="diag-big">${pct(d.porcentaje_diagnosticado)}</div><div class="diag-grid"><span>Universo: <strong>${fmt(d.total_acueductos)}</strong></span><span>Diagnosticados: <strong>${fmt(d.diagnosticados)}</strong></span><span>Por diagnosticar: <strong>${fmt(d.por_validar)}</strong></span><span>Afectados: <strong>${fmt(d.afectados)}</strong></span><span>Población afectada: <strong>${fmt(d.poblacion_afectada)}</strong></span><span>Inversión: <strong>${moneyM(d.inversion_total)}</strong></span></div><button class="btn tiny filter-map-mun" data-mun="${esc(d.municipio)}" style="margin-top:10px">Filtrar tablero por municipio</button>`;target.querySelector('.filter-map-mun')?.addEventListener('click',e=>{qs('#filter-mun').value=e.currentTarget.dataset.mun;onFilterChange();qsa('.modal.open').forEach(m=>closeModal(m.id));});}
  function buildDiagnosticRank(){const arr=MUN.slice().sort((a,b)=>b.porcentaje_diagnosticado-a.porcentaje_diagnosticado||b.total_acueductos-a.total_acueductos);const html=arr.map(d=>`<div class="diag-rank-row" data-mun="${esc(d.municipio)}"><span>${esc(d.municipio)}</span><strong>${pct(d.porcentaje_diagnosticado)}</strong></div>`).join('');qs('#diagnostic-ranking').innerHTML=html;qs('#diagnostic-ranking-mini').innerHTML=html;qsa('.diag-rank-row').forEach(r=>r.addEventListener('click',()=>{const d=MUN.find(x=>x.municipio===r.dataset.mun);SELECTED_MUN=d.municipio;showMunicipalDiagnostic(d,r.closest('.map-side')?qs('#map-selected-modal'):qs('#map-selected'));renderAllMaps();}));}
  function renderAllMaps(){renderGeoMap('valle-map','map-selected','map-tooltip');if(qs('#diagnostic-map-modal').classList.contains('open'))renderGeoMap('valle-map-modal','map-selected-modal','map-tooltip-modal');}
  function openDiagnosticMap(){qs('#map-universe').textContent=fmt(META.universo_acueductos);qs('#map-diagnosed').textContent=fmt(META.diagnosticados);qs('#map-pct').textContent=pct(META.porcentaje_diagnosticado);openModal('diagnostic-map-modal');setTimeout(()=>renderGeoMap('valle-map-modal','map-selected-modal','map-tooltip-modal'),20);}
  qs('#expand-map').addEventListener('click',openDiagnosticMap);

  initTheme();renderKPIs();initTabs();initFilters();renderSummary();renderMunicipalRanking();renderAffectedSummary();renderCards();renderPriorityTable();renderInvestments();renderMethodology();buildDiagnosticRank();renderAllMaps();
})();
